### ISSUE TITLE
Burst-triggered frames

### ISSUE THREAD

**Issue by YuBehaviorLab** [jiumao2/Yu-Lab#3]
Burst

plot spikes (raster) +/- 1 sec (new axis below the image)

10 frames marked
mark relative time (xtick: -1000:200:1000 ms)

**Comment by jiumao2** [comment]
Raw Video:
![Unit1](https://user-images.githubusercontent.com/62061407/157700735-1139cb77-151c-4f61-835b-879465176c11.gif)

Plot spikes (raster) +/- 0.5 sec:
![Unit1_clip](https://user-images.githubusercontent.com/62061407/157700951-a9e37326-bf5d-4a86-8525-d5b51059c48a.gif)
