### ISSUE TITLE
release or press?

### ISSUE THREAD

**Issue by YuBehaviorLab** [jiumao2/Yu-Lab#4]
check psth (traj.-dependent)

**Comment by jiumao2** [comment]
Bug: release time = press time + reaction time
Now: release time = press time + foreperiod + reaction time

Bug fixed

Press:
![TrajComparing_Unit1_Press](https://user-images.githubusercontent.com/62061407/157438050-413b6a6e-c1aa-4628-a7d8-8b97cfcb5c33.png)
Release(bug)
![TrajComparing_Unit1_Release_bug](https://user-images.githubusercontent.com/62061407/157438063-aa73fffc-314c-4569-ae82-4eab20172da9.png)
Release(new)
![TrajComparing_Unit1_Release](https://user-images.githubusercontent.com/62061407/157438026-0018130d-50b7-4898-913b-28658332cf01.png)
